version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"